name: CI/CD Pipeline

on:
  push:
    branches:
      - master        
  pull_request:
    branches:
      - master        

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js (Backend)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install 

  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js (Frontend)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install  
